### ISSUE TITLE
App Delegate

### ISSUE THREAD

**Issue by mcdappdev** [Theteateam/teatime#1]
On run time app generates an error because of a missing app delegate file. @andysolomon may have accidentally moved it into his trash, as that's what the error looks like. If that's the case you'll need to either create a new one or find it in your trash and redeploy asap.

**Comment by andysolomon** [comment]
AppDelegate.swift was placed in the 'Supporting Files' directory. I've never touched the file, but do you( @mcdappdev  ) think we should add it back to the root.
